-- Delete the literals from Barometer (Literal id 20000-29999)
DELETE FROM literal WHERE id >= 20000 AND id < 30000;
-- Delete the charts from Barometer (Chart id 20000-29999)
DELETE FROM chart WHERE id >= 20000 AND id < 30000;

-- Create Database Table for the pages
-- Enforcement Capacity, Regulation, Strategy and Methodology
DROP TABLE IF EXISTS `matrix_page`;
CREATE TABLE IF NOT EXISTS `matrix_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page` varchar(50) NOT NULL,
  `nuts_id` int(11) NOT NULL,
  `check_1` tinyint(4) DEFAULT '0',
  `check_2` tinyint(4) DEFAULT '0',
  `check_3` tinyint(4) DEFAULT '0',
  `check_4` tinyint(4) DEFAULT '0',
  `text_1_literal_id` int(11) DEFAULT NULL,
  `text_2_literal_id` int(11) DEFAULT NULL,
  `text_3_literal_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `matrix_text_1_literal_id` (`text_1_literal_id`),
  KEY `matrix_text_2_literal_id` (`text_2_literal_id`),
  KEY `matrix_text_3_literal_id` (`text_3_literal_id`),
  KEY `matrix_nuts_id` (`nuts_id`),
  CONSTRAINT `matrix_nuts_id` FOREIGN KEY (`nuts_id`) REFERENCES `nuts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `matrix_text_1_literal_id` FOREIGN KEY (`text_1_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `matrix_text_2_literal_id` FOREIGN KEY (`text_2_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `matrix_text_3_literal_id` FOREIGN KEY (`text_3_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `strategies_page`;
CREATE TABLE IF NOT EXISTS `strategies_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page` varchar(50) NOT NULL,
  `nuts_id` int(11) NOT NULL,
  `text_1_literal_id` int(11) DEFAULT NULL,
  `text_2_literal_id` int(11) DEFAULT NULL,
  `text_3_literal_id` int(11) DEFAULT NULL,
  `text_4_literal_id` int(11) DEFAULT NULL,
  `text_5_literal_id` int(11) DEFAULT NULL,
  `text_6_literal_id` int(11) DEFAULT NULL,
  `text_7_literal_id` int(11) DEFAULT NULL,
  `text_8_literal_id` int(11) DEFAULT NULL,
  `text_9_literal_id` int(11) DEFAULT NULL,
  `text_10_literal_id` int(11) DEFAULT NULL,
  `text_11_literal_id` int(11) DEFAULT NULL,
  `text_12_literal_id` int(11) DEFAULT NULL,
  `text_13_literal_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `nuts_id` (`nuts_id`),
  KEY `strategies_text_1_literal_id` (`text_1_literal_id`),
  KEY `strategies_text_2_literal_id` (`text_2_literal_id`),
  KEY `strategies_text_3_literal_id` (`text_3_literal_id`),
  KEY `strategies_text_4_literal_id` (`text_4_literal_id`),
  KEY `strategies_text_5_literal_id` (`text_5_literal_id`),
  KEY `strategies_text_6_literal_id` (`text_6_literal_id`),
  KEY `strategies_text_7_literal_id` (`text_7_literal_id`),
  KEY `strategies_text_8_literal_id` (`text_8_literal_id`),  
  KEY `strategies_text_9_literal_id` (`text_9_literal_id`),
  KEY `strategies_text_10_literal_id` (`text_10_literal_id`),
  KEY `strategies_text_11_literal_id` (`text_11_literal_id`),
  KEY `strategies_text_12_literal_id` (`text_12_literal_id`),
  KEY `strategies_text_13_literal_id` (`text_13_literal_id`),
  CONSTRAINT `strategies_nuts_id_fk` FOREIGN KEY (`nuts_id`) REFERENCES `nuts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_1_literal_id` FOREIGN KEY (`text_1_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_2_literal_id` FOREIGN KEY (`text_2_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_3_literal_id` FOREIGN KEY (`text_3_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_4_literal_id` FOREIGN KEY (`text_4_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_5_literal_id` FOREIGN KEY (`text_5_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_6_literal_id` FOREIGN KEY (`text_6_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_7_literal_id` FOREIGN KEY (`text_7_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_8_literal_id` FOREIGN KEY (`text_8_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_9_literal_id` FOREIGN KEY (`text_9_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_10_literal_id` FOREIGN KEY (`text_10_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_11_literal_id` FOREIGN KEY (`text_11_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_12_literal_id` FOREIGN KEY (`text_12_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `strategies_text_13_literal_id` FOREIGN KEY (`text_13_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `methodology`;
CREATE TABLE `methodology` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `indicator_id` int(11) NOT NULL,
  `dataset_id` int(11) NOT NULL,
  `section_id` int(11) NOT NULL,
  `additional_comments_literal_id` int(11) DEFAULT NULL,
  `description_literal_id` int(11) DEFAULT NULL,
  `source_methodology_literal_id` int(11) DEFAULT NULL,
  `specific_table_literal_id` int(11) DEFAULT NULL,
  `url_literal_id` int(11) DEFAULT NULL,
  `reference_year_literal_id` int(11) DEFAULT NULL,
  `last_update_literal_id` int(11) DEFAULT NULL,
  `coverage_literal_id` int(11) DEFAULT NULL,
  `filtering_options_literal_id` int(11) DEFAULT NULL,
  `calculations_literal_id` int(11) DEFAULT NULL,
  `unit_measure_literal_id` int(11) DEFAULT NULL,
  `visualisation_literal_id` int(11) DEFAULT NULL,
  `indicator_name_displayed_literal_id` int(11) DEfAULT NULL,
  PRIMARY KEY (`id`),
  KEY `methodology_indicator_id` (`indicator_id`),
  KEY `methodology_dataset_id` (`dataset_id`),
  KEY `methodology_section_id` (`section_id`),
  KEY `methodology_additional_comments_literal_id` (`additional_comments_literal_id`),
  KEY `methodology_description_literal_id` (`description_literal_id`),
  KEY `methodology_source_methodology_literal_id` (`source_methodology_literal_id`),
  KEY `methodology_specific_table_literal_id` (`specific_table_literal_id`),
  KEY `methodology_url_literal_id` (`url_literal_id`),
  KEY `methodology_reference_year_literal_id` (`reference_year_literal_id`),
  KEY `methodology_last_update_literal_id` (`last_update_literal_id`),
  KEY `methodology_coverage_literal_id` (`coverage_literal_id`),
  KEY `methodology_filtering_options_literal_id` (`filtering_options_literal_id`),
  KEY `methodology_calculations_literal_id` (`calculations_literal_id`),
  KEY `methodology_unit_measure_literal_id` (`unit_measure_literal_id`),
  KEY `methodology_visualisation_literal_id` (`visualisation_literal_id`),
  KEY `methodology_indicator_name_displayed_literal_id` (`indicator_name_displayed_literal_id`),
  CONSTRAINT `methodology_indicator_id` FOREIGN KEY (`indicator_id`) REFERENCES `indicator` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_dataset_id` FOREIGN KEY (`dataset_id`) REFERENCES `dataset` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_section_id` FOREIGN KEY (`section_id`) REFERENCES `section` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_additional_comments_literal_id` FOREIGN KEY (`additional_comments_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_description_literal_id` FOREIGN KEY (`description_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_source_methodology_literal_id` FOREIGN KEY (`source_methodology_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_specific_table_literal_id` FOREIGN KEY (`specific_table_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_url_literal_id` FOREIGN KEY (`url_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_reference_year_literal_id` FOREIGN KEY (`reference_year_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_last_update_literal_id` FOREIGN KEY (`last_update_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_coverage_literal_id` FOREIGN KEY (`coverage_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_filtering_options_literal_id` FOREIGN KEY (`filtering_options_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_calculations_literal_id` FOREIGN KEY (`calculations_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_unit_measure_literal_id` FOREIGN KEY (`unit_measure_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_visualisation_literal_id` FOREIGN KEY (`visualisation_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `methodology_indicator_name_displayed_literal_id` FOREIGN KEY (`indicator_name_displayed_literal_id`) REFERENCES `literal` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;