DROP TABLE IF EXISTS `figure_norm`;
CREATE TABLE IF NOT EXISTS `figure_norm` (
  `INDICATOR_ID` smallint(6) DEFAULT NULL,
  `YEAR`varchar(255) DEFAULT NULL,
  `REGION` varchar(15) DEFAULT NULL,
  `COUNTRY` varchar(50) DEFAULT NULL,
  `MEASURE` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
